remote_theme: brianmaierjr/uni
title: "План чтения Библии за год"
# Description of your website. This is used for social sharing.
description:  "В предлагаемом плане Ветхий и Новый заветы читаются параллельно. Он доступен для скачивания как в виде модуля для приложения MyBible, так и в виде трёх вариантов для печати (в формате PDF): «Обычный», «Молодёжный», «Крупный шрифт»."

# A brief blurb about yourself
# content: "В предлагаемом плане Ветхий и Новый заветы читаются параллельно. Доступен и в виде модуля для приложения <a href="https://mybible.zone" title="сайт приложения MyBible">MyBible</a>, и в виде трёх вариантов для печати (в формате PDF):"

# Add your download links    
download:
  - platform: Обычный
    url: ./download/commonplan.pdf
  - platform: Молодёжный
    url: ./download/youthplan.pdf
  - platform: "Крупный шрифт"
    url: ./download/eldersplan.pdf
  - platform: "Модуль MyBible"
    url: ./download/NOVCHURCH-p.plan.SQLite3

# General settings
url: https://novchurch.github.io
baseurl: "/plan" 
markdown: kramdown
sharing_image: half-sm.jpg
# google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  ignore:
    envs: [local]
    
sass:
  style: compressed
